# Generated by Django 4.2.7 on 2024-05-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_imgs')),
                ('link', models.CharField(max_length=200)),
                ('title', models.CharField(default='Food', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_imgs')),
                ('discount_deal', models.CharField(choices=[('hot deals', 'HOT DEALS'), ('new arrivals', 'NEW ARRIVALS')], max_length=100)),
                ('sale', models.IntegerField()),
                ('brand_name', models.CharField(max_length=200)),
                ('discount', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
