# Generated by Django 4.2 on 2024-12-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_status_alter_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_period_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
